### ISSUE TITLE
Invalid spring controller generated

### ISSUE THREAD

**Issue by systemfreund** [MaSch0212/goast#29]
Given the following spec:

```yaml
openapi: 3.1.0
paths:
  /foo:
    post:
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FooRequest'

components:
  schemas:
    FooRequest:
      type: object
      properties:
        bar:
          type: boolean
          default: false
```

goast currently creates the following spring controller:

```kotlin
interface FooApi {
    [...]
    @RequestMapping(method = [RequestMethod.POST], value = ["/foo"], consumes = ["multipart/form-data"])
    suspend fun foo(
        @Parameter(
            [...]
            required = false,
            schema = Schema(defaultValue = "false")
        )
        @RequestPart(value = "bar", required = false)
        bar: Boolean
    ): ResponseEntity [...]
}
```

While the schema defines a `defaultValue=false` it does not create the proper function signature, which would be:

`bar: Boolean = false`

Failing to do so causes a `NullPointerException` at runtime, when a request is made where the optional `bar` parameter is absent.
An absent `bar` parameter maps to `null` which is incompatible with the specified type `Boolean`.

**Comment by MaSch0212** [comment]
Fix is available in @goast/kotlin@0.4.3
